
wf-plan1-20260707-001Test Documentation¤

REQ-UI-0016Formulario de registro con nombre y email obligatoriosVLa UI debe impedir el envio cuando nombre o email faltan y permitir telefono opcional."*el usuario abre la pagina de registro en /"1el formulario contiene campos name, email y phone*>el usuario intenta enviar el formulario con name o email vacio2=el navegador bloquea el submit por validacion HTML5 requerida2.no debe mostrarse mensaje de exito de registro:public/index.html:16:public/index.html:21:tests/ui/form.spec.ts:42:tests/ui/form.spec.ts:49:tests/ui/form.spec.ts:62í

REQ-UI-002+Email debe respetar formato valido en la UIOEl input de email debe rechazar formatos no validos antes de enviar al backend."%el usuario completa nombre y telefono"%el usuario escribe un email no valido*el usuario presiona Registrarse2"la validacion HTML5 evita el envio2no debe verse mensaje de exito:public/index.html:21:tests/ui/form.spec.ts:32÷

REQ-UI-003,Registro exitoso muestra feedback al usuariowAnte respuesta 2xx de /api/register se debe mostrar mensaje de exito, limpiar formulario y ocultar mensaje luego de 3s."(el usuario completa name y email validos" el backend responde success=true*!se procesa el submit en script.js2*se muestra texto Registro exitoso. Gracias2el formulario se reinicia24el mensaje vuelve a estado vacio luego de 3 segundos:public/script.js:20:public/script.js:23:public/script.js:25:tests/ui/form.spec.ts:9Ô
REQ-NAV-001$Navegacion entre Registro y UsuariosVLa aplicacion debe permitir moverse de / a /users y viceversa mediante links visibles."2el usuario visualiza cualquiera de las dos paginas*#hace click en enlaces de navegacion2!se carga la ruta destino esperada24el estado active del enlace refleja la pagina actual:public/index.html:35:public/index.html:36:public/users.html:28:public/users.html:29:tests/ui/navigation.spec.ts:7:tests/ui/navigation.spec.ts:16°
REQ-API-0015POST /api/register crea usuario con campos requeridos\La API debe aceptar name y email obligatorios, con phone opcional, y devolver JSON de exito.""existe endpoint POST /api/register"el body request es JSON*(name y email estan presentes y no vacios2la respuesta es 2002%content-type incluye application/json2,el usuario creado contiene id y registeredAt2&el usuario queda almacenado en memoria:server.js:151:server.js:157:server.js:165: tests/api/register.api.spec.ts:6:!tests/api/register.api.spec.ts:17:!tests/api/register.api.spec.ts:84¬
REQ-API-0027Validacion de requeridos en API para crear y actualizarWPOST /api/register y PUT /api/users/:id deben responder 400 cuando name o email faltan."9el cliente invoca POST /api/register o PUT /api/users/:id*%name o email vienen vacios o ausentes2la API responde 40021el body incluye error Name and email are required:server.js:97:server.js:157:!tests/api/register.api.spec.ts:49:!tests/api/register.api.spec.ts:73•
REQ-API-003'Gestion CRUD parcial de usuarios por id`La API debe permitir consultar, actualizar y eliminar usuarios por id con 404 cuando no existan."6hay usuarios previamente registrados o id inexistentes*7el cliente llama GET, PUT o DELETE sobre /api/users/:id2,GET retorna usuario y 200 o 404 si no existe27PUT actualiza y retorna success=true o 404 si no existe28DELETE elimina y retorna success=true o 404 si no existe:server.js:77:server.js:91:server.js:131:tests/api/users.api.spec.ts:13:tests/api/users.api.spec.ts:33Ó

REQ-UI-0045Listado de usuarios con acciones de editar y eliminarzLa pantalla de usuarios debe cargar /api/users al iniciar, renderizar tabla, editar por modal y eliminar con confirmacion."el usuario entra a /users*8la pagina dispara DOMContentLoaded y eventos de acciones20se consulta GET /api/users y se renderizan filas2-editar ejecuta PUT /api/users/:id desde modal2>eliminar solicita confirmacion y ejecuta DELETE /api/users/:id:public/users-script.js:2:public/users-script.js:34:public/users-script.js:75:public/users-script.js:107:public/users-script.js:130:public/users.html:39"Õ
FLOW-001AAlta de usuario desde formulario UI hasta persistencia en memoria)GIVEN usuario en / con formulario visible*WHEN completa name y email validos y envia/THEN frontend llama POST /api/register con JSONBTHEN backend crea user con id y registeredAt y lo agrega a users[]:THEN frontend muestra mensaje de exito y limpia formulario"›
FLOW-002-Navegacion y consulta de usuarios registrados#GIVEN usuario en pagina de registro"WHEN navega a /users desde el menu)THEN users-script solicita GET /api/users7THEN si lista vacia muestra No hay usuarios registrados3THEN si lista no vacia renderiza tabla con acciones"ž
FLOW-003Edicion de usuario existente/GIVEN usuario visualiza fila en tabla de /users0WHEN presiona Editar y confirma cambios en modal2THEN frontend obtiene datos por GET /api/users/:id&THEN frontend envia PUT /api/users/:id5THEN recarga listado y notifica actualizacion exitosa"¤
FLOW-004.Eliminacion de usuario con confirmacion previa/GIVEN usuario visualiza fila en tabla de /users,WHEN presiona Eliminar y acepta confirmacion)THEN frontend envia DELETE /api/users/:id+THEN backend elimina registro o retorna 4041THEN frontend refresca tabla y notifica resultado*†
RISK-001Persistencia volatil en memoriagPerdida total de datos al reiniciar servidor, afecta repetibilidad de pruebas y trazabilidad historica."pInicializar data de prueba por setup de tests y contemplar almacenamiento persistente para ambientes integrados.*ø
RISK-002'Validacion de formato incompleta en APIbAPI acepta emails y telefonos mal formados si pasan presencia minima, degradando calidad de datos."_Agregar validaciones de formato server-side y activar casos API actualmente marcados como skip.*ë
RISK-003(Desalineacion de contrato HTTP en READMEkREADME menciona 201 para registro pero implementacion y tests validan 200, generando confusiones de oracle."HUnificar contrato en README y suites para un codigo de estado canonical.*Ë
RISK-004,Id basado en Date.now con riesgo de colisionOCreaciones concurrentes podrian compartir id y afectar operaciones por recurso."@Migrar a UUID o secuencia monotona robusta para identificadores.*Ë
RISK-005%Cobertura incompleta por pruebas skipAEscenarios clave de error y delete no se validan automaticamente."UHabilitar casos skip y agregar datos controlados para pruebas negativas y de borrado.2s
DEP-001Node.js runtimeWEjecucion de servidor HTTP y scripts de soporte; requisito minimo documentado Node 12+.2j
DEP-002
protobufjsSSerializacion y validacion de artefactos .pb contra .github/spec/qa_workflow.proto.2~
DEP-003Playwright TestbSuite de pruebas UI/API existente utilizada como fuente de trazabilidad y comportamiento esperado.2
DEP-004Contrato qa_workflow.protoXEsquema canonical machine-first requerido para DocumentationHandoff en flujo orquestado.2˜
DEP-005&API interna /api/users y /api/registereSuperficie funcional del sistema bajo prueba para flows de registro, consulta, edicion y eliminacion.