
wf-plan1-20260707-001Test GeneratorŸ

PLN-UI-001ABloquear envio cuando faltan campos obligatorios en el formulario5Aplicacion web disponible en / con formulario visible.Campos name y email marcados como obligatorios"$Navegar a la pagina de registro (/)."Dejar el campo name vacio."=Completar email con valor valido (ejemplo: user@example.com)."Hacer click en Registrarse."5Repetir variando: completar name y dejar email vacio.*FEl navegador bloquea el submit por validacion HTML5 en ambos intentos.*)No se emite request POST a /api/register.*No se muestra mensaje de exito.à

PLN-UI-002)Rechazar email con formato invalido en UIAplicacion web disponible en /$Campo name completo con valor valido"$Navegar a la pagina de registro (/)." Completar name con texto valido."-Ingresar email invalido (ejemplo: invalido@)."Hacer click en Registrarse."DRepetir con variante edge: email sin arroba (ejemplo: invalido.com).*;La validacion de tipo email impide el envio del formulario.*)No se emite request POST a /api/register.*No se muestra mensaje de exito.è

PLN-UI-0039Mostrar feedback de registro exitoso y limpiar formularioAplicacion web disponible en //API /api/register responde 2xx con success=true"$Navegar a la pagina de registro (/)." Completar name con valor valido."!Completar email con valor valido."5Completar phone con valor opcional (o dejarlo vacio)."Hacer click en Registrarse."<Esperar hasta 3 segundos para verificar limpieza de mensaje.*6Se ejecuta POST /api/register con payload JSON valido.*0Se muestra feedback visible de registro exitoso.**El formulario se reinicia (campos vacios).*;El mensaje de exito se oculta o vacia luego de ~3 segundos.¬
PLN-NAV-001CNavegar entre vistas Registro y Usuarios con estado activo correcto'Aplicacion web disponible en / y /users-Links de navegacion visibles en ambas paginas" Abrir la pagina de registro (/).".Verificar que el link de Registro este activo."Hacer click en link Usuarios.";Verificar carga de /users y estado activo en link Usuarios."Hacer click en link Registro."7Verificar retorno a / y estado activo en link Registro.*4La navegacion entre / y /users funciona sin errores.*DEl enlace activo refleja correctamente la vista actual en cada paso.³

PLN-UI-004?Cargar y operar listado de usuarios (render, editar y eliminar)#Aplicacion web disponible en /users:API /api/users operativa con al menos un usuario de prueba"Abrir /users."DVerificar que se dispare carga inicial de la tabla (GET /api/users)."-Confirmar que se renderiza al menos una fila."?Ejecutar accion Editar sobre un usuario y cambiar name o email."Confirmar guardado en modal."GEjecutar accion Eliminar sobre el mismo usuario y aceptar confirmacion.*'La tabla se renderiza con datos de API.*6Editar dispara PUT /api/users/:id y actualiza la fila.*?Eliminar solicita confirmacion y dispara DELETE /api/users/:id.*5La tabla refleja los cambios luego de cada operacion.»
PLN-API-REG-0011Crear usuario exitosamente con POST /api/register;Servidor levantado y endpoint POST /api/register disponible)Request con Content-Type application/json"BEnviar POST /api/register con body valido: name y email no vacios."0Registrar status code y headers de la respuesta."$Inspeccionar body JSON de respuesta."2Consultar listado de usuarios para confirmar alta.*Respuesta HTTP 200.*-Header content-type incluye application/json.*>Body incluye success=true y objeto user con id y registeredAt.*9El usuario queda disponible para operaciones posteriores.–
PLN-API-REG-002<Rechazar payload sin campos requeridos en POST /api/register;Servidor levantado y endpoint POST /api/register disponible/Cliente capaz de enviar payloads JSON invalidos"6Enviar POST /api/register sin name y con email valido."6Enviar POST /api/register con name valido y sin email."2Enviar POST /api/register con name y email vacios."(Registrar status y body de cada intento.*'Cada request invalido retorna HTTP 400.*1Body de error indica Name and email are required.*-No se crean usuarios para payloads invalidos.Ó
PLN-API-USR-0010Consultar usuario por id existente e inexistente-Existe al menos un usuario creado previamente.Se dispone de un id valido y un id inexistente"*Ejecutar GET /api/users/:id con id valido."-Registrar status y body de respuesta exitosa."/Ejecutar GET /api/users/:id con id inexistente.".Registrar status y body de respuesta negativa.*1Con id valido, retorna HTTP 200 y objeto usuario.*@Con id inexistente, retorna HTTP 404 con error de no encontrado.…
PLN-API-USR-0028Actualizar usuario por id con validacion y manejo de 404-Existe al menos un usuario creado previamente&Endpoint PUT /api/users/:id disponible"?Enviar PUT /api/users/:id valido con name y email actualizados."+Verificar status y body del update exitoso."GEnviar PUT /api/users/:id con payload invalido (name o email faltante).">Enviar PUT /api/users/:id con id inexistente y payload valido."/Registrar status y body de los tres escenarios.*0Update valido retorna HTTP 200 con success=true.*JPayload invalido retorna HTTP 400 con mensaje Name and email are required.*;Id inexistente retorna HTTP 404 con error de no encontrado.š
PLN-API-USR-003/Eliminar usuario por id existente e inexistente(Existe al menos un usuario para eliminar)Endpoint DELETE /api/users/:id disponible"0Ejecutar DELETE /api/users/:id con id existente."/Verificar status y body de eliminacion exitosa."3Repetir DELETE sobre el mismo id o uno inexistente."1Registrar status y body de la respuesta negativa.*4Con id existente, retorna HTTP 200 con success=true.*@Con id inexistente, retorna HTTP 404 con error de no encontrado.*>El usuario eliminado ya no se recupera por GET /api/users/:id."
PLN-UI-001"
PLN-UI-002"
PLN-UI-003"PLN-NAV-001"
PLN-UI-004"PLN-API-REG-001"PLN-API-REG-002"PLN-API-USR-001"PLN-API-USR-002"PLN-API-USR-003